name: grisp_connect CT

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Erlang/OTP ${{matrix.otp}} / rebar3 ${{matrix.rebar3}}
    strategy:
      matrix:
        otp: ['27.1']
        rebar3: ['3.24.0']
    steps:
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}
      - uses: actions/checkout@v2
      - name: Compiling
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.STRITZINGER_BOT_SSH_KEY }}'
          rebar3 as test compile
      - name: Run ct
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.STRITZINGER_BOT_SSH_KEY }}'
          rebar3 ct
      - name: Run ex_doc
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.STRITZINGER_BOT_SSH_KEY }}'
          rebar3 ex_doc
